# Generated by Django 4.2.3 on 2023-09-04 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_remove_project_content_remove_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
