# Generated by Django 4.2.3 on 2023-09-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rename_author_project_writer_project_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
    ]
